### ISSUE TITLE
shifter_classic_components: issue with arm 2jnt_freeTangents & leg 2jnt_freeTangents

### ISSUE THREAD

**Issue by adamavery** [mgear-dev/shifter_classic_components#33]
Orientation of deformers in both 2jnt_freeTangents & leg 2jnt_freeTangents seems to be strange, very hard to get good results when skinning.(see example attached)
![arm_issue](https://user-images.githubusercontent.com/46025023/50286277-d512fa00-0456-11e9-962f-1318d6529d20.jpg)

**Comment by miquelcampos** [comment]
Hi @adamavery Thanks for the feedback. and sorry for the late reply. I will try to check this on new year holidays.

**Comment by miquelcampos** [comment]
Hi @adamavery 
I have been checking this issue and here are the conclusions and solution/workarounds (I post this here just in case other people has the same questions/issue  :) )

**For the first issue:**
for this, the easiest solution for the elbow and knee mid-rotation is just add a gimmick blended joint:
![image](https://user-images.githubusercontent.com/1050212/50906369-42b7b200-1468-11e9-8de8-88535f22d436.png)
after creation, you will see the new blended joint (yellow color)
![image](https://user-images.githubusercontent.com/1050212/50906440-70046000-1468-11e9-8754-c69267c446b8.png)

the process can be scripted. Check this video: https://www.youtube.com/watch?v=-JFPD3k3Sl4&t=8s

**For the second issue:**
About the way is calculating the rotation for round arms. I can't change it. This is something related to the solver itself.  
In the arm_2jnt_01 we are using the custom mgear roll spline solver. For the arm_2jnt_freetangent we are using the default Maya spline IK.
I am talking about the differences and how to skin it in this video: https://www.youtube.com/watch?v=g5oEkXz_vaE

**Fun fact**:  I have received last year same request but the other way. the freetangent orientation style in the regular arm :P 
 I am sorry that I can't change this since it is the way that the solvers are design

Best regards,
Miquel
